module.exports = {
    current: [
        'Javascript (ES6), TypeScript or Coffeescript if necessary',
        'NodeJS &amp; NPM',
        'Express, WebSockets',
        'AngularJS, Backbone, Underscore JS / Lodash',
        'React, JSX, Redux, Babel',
        'D3, NVD3, Highcharts, Chart.js',
        'Webpack, Babel, Browserify, Uglify, Grunt, Gulp',
        'Git, Gitflow, Semantic Versioning',
        'Jest, Mocha, Chai, Sinon, JSDom, Phantom',
        'LESS, SASS &amp; Stylus',
        'Jade / Pug',
        'Bash, zsh, Make',
        'jQuery (obviously)',
    ],
    software: [
        'Google Chrome',
        'Sublime Text, vim',
        'Github, tig',
        'iTerm2',
        'Spotify',
        'Stack Overflow',
    ],
    previous: [
        'PHP7, Composer, PHPUnit',
        'PHP 5.3, Symfony 1.4, Doctrine, Zend Framework, Code Igniter',
        'MySQL',
        'Apache',
        'ASP .NET (C#)',
        'Microsoft Windows, IIS, SQL Server, Visual Studio 2010',
        'Mercurial (HG), Subversion (SVN)',
        'Java &amp; JSP',
        'Photoshop, Gimp',
        'Google Maps API',
        'Fogbugz, Kiln, JIRA, Bitbucket, Stash',
        'Heroku, Appfog, cPanel, WHM, Nodejitsu',
        'Selenium',
        'Vagrant',
    ],
    some: [
        'MongoDB, Redis',
        'Docker',
        'Symfony2, Laravel',
        'Meteor, Sails, Brunch, Marionette',
        'PhoneGap / Cordova',
    ],
    interested: [
        'Any language other than Javascript',
        'Relay',
        'GraphQL',
        'ElasticSearch',
    ]
}
